# order or inclusion matters!
include(joinpath(@__DIR__, "TestLiveProgress.jl"))
include(joinpath(@__DIR__, "TestLiveIcons.jl"))
include(joinpath(@__DIR__, "TestLiveCard.jl"))
include(joinpath(@__DIR__, "TestLiveCardRows.jl"))
include(joinpath(@__DIR__, "TestLiveInteraction.jl"))
include(joinpath(@__DIR__, "TestLiveTree.jl"))
include(joinpath(@__DIR__, "TestLiveView.jl"))
include(joinpath(@__DIR__, "TestLiveSelection.jl"))
include(joinpath(@__DIR__, "TestLiveWidgetRecipe.jl"))
include(joinpath(@__DIR__, "TestLiveApp.jl"))
include(joinpath(@__DIR__, "TestLiveDock.jl"))
include(joinpath(@__DIR__, "TestLiveInspector.jl"))
include(joinpath(@__DIR__, "TestLiveExtras.jl"))
include(joinpath(@__DIR__, "TestLiveCustom.jl"))
include(joinpath(@__DIR__, "TestViewCube.jl"))
include(joinpath(@__DIR__, "TestAgentSkill.jl"))
